[2023-12-23T15:50:24.471+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T14:51:21.363093+00:00 [queued]>
[2023-12-23T15:50:24.483+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T14:51:21.363093+00:00 [queued]>
[2023-12-23T15:50:24.483+0000] {taskinstance.py:2171} INFO - Starting attempt 6 of 6
[2023-12-23T15:50:24.672+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_raw_data_to_postgres> on 2023-12-23 14:51:21.363093+00:00
[2023-12-23T15:50:24.677+0000] {standard_task_runner.py:60} INFO - Started process 50 to run task
[2023-12-23T15:50:24.682+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'load_raw_data_to_postgres', 'manual__2023-12-23T14:51:21.363093+00:00', '--job-id', '1356', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmp9dv7fngz']
[2023-12-23T15:50:24.686+0000] {standard_task_runner.py:88} INFO - Job 1356: Subtask load_raw_data_to_postgres
[2023-12-23T15:50:24.744+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T14:51:21.363093+00:00 [running]> on host 417a45a22e6c
[2023-12-23T15:50:24.844+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='10 academy' AIRFLOW_CTX_DAG_ID='dag_to_dum_raw_data_to_postgres' AIRFLOW_CTX_TASK_ID='load_raw_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T14:51:21.363093+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-23T14:51:21.363093+00:00'
[2023-12-23T15:50:40.067+0000] {warnings.py:109} WARNING - /opt/***/dags/dump_raw_data_to_postgres.py:30: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  df = pd.read_csv(file_path,index_col=False, delimiter='; ', engine='python')

[2023-12-23T15:51:10.108+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dump_raw_data_to_postgres.py", line 33, in write_to_database
    csv_data = load_csv_as_list(file_path)
  File "/opt/airflow/dags/dump_raw_data_to_postgres.py", line 23, in load_csv_as_list
    csv_reader = csv.reader(file, delimiter=";")
NameError: name 'csv' is not defined
[2023-12-23T15:51:10.130+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_to_dum_raw_data_to_postgres, task_id=load_raw_data_to_postgres, execution_date=20231223T145121, start_date=20231223T155024, end_date=20231223T155110
[2023-12-23T15:51:10.172+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1356 for task load_raw_data_to_postgres (name 'csv' is not defined; 50)
[2023-12-23T15:51:10.232+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T15:51:10.261+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
