[2023-12-23T13:43:13.674+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T13:38:08.712123+00:00 [queued]>
[2023-12-23T13:43:13.686+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T13:38:08.712123+00:00 [queued]>
[2023-12-23T13:43:13.687+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-23T13:43:13.853+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): load_raw_data_to_postgres> on 2023-12-23 13:38:08.712123+00:00
[2023-12-23T13:43:13.859+0000] {standard_task_runner.py:60} INFO - Started process 327 to run task
[2023-12-23T13:43:13.863+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'load_raw_data_to_postgres', 'manual__2023-12-23T13:38:08.712123+00:00', '--job-id', '1226', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmpyqy6t08u']
[2023-12-23T13:43:13.866+0000] {standard_task_runner.py:88} INFO - Job 1226: Subtask load_raw_data_to_postgres
[2023-12-23T13:43:13.930+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T13:38:08.712123+00:00 [running]> on host 51dca2e3ed8e
[2023-12-23T13:43:14.051+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='10 academy' AIRFLOW_CTX_DAG_ID='dag_to_dum_raw_data_to_postgres' AIRFLOW_CTX_TASK_ID='load_raw_data_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T13:38:08.712123+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-23T13:38:08.712123+00:00'
[2023-12-23T13:43:14.053+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: write_to_database() missing 1 required positional argument: 'self'
[2023-12-23T13:43:14.066+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_to_dum_raw_data_to_postgres, task_id=load_raw_data_to_postgres, execution_date=20231223T133808, start_date=20231223T134313, end_date=20231223T134314
[2023-12-23T13:43:14.085+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1226 for task load_raw_data_to_postgres (write_to_database() missing 1 required positional argument: 'self'; 327)
[2023-12-23T13:43:14.115+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T13:43:14.136+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
