[2023-12-23T14:15:58.720+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_to_dum_raw_data_to_postgres.load_raw_data_to_postgres manual__2023-12-23T13:33:41.055010+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
