[2023-12-23T11:44:35.580+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_to_dum_raw_data_to_postgres.create_postgres_table scheduled__2003-01-10T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
