[2023-12-23T16:47:18.099+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.run_dbt manual__2023-12-23T16:37:11.087925+00:00 [queued]>
[2023-12-23T16:47:18.111+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.run_dbt manual__2023-12-23T16:37:11.087925+00:00 [queued]>
[2023-12-23T16:47:18.111+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 6
[2023-12-23T16:47:18.128+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): run_dbt> on 2023-12-23 16:37:11.087925+00:00
[2023-12-23T16:47:18.134+0000] {standard_task_runner.py:60} INFO - Started process 819 to run task
[2023-12-23T16:47:18.139+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'run_dbt', 'manual__2023-12-23T16:37:11.087925+00:00', '--job-id', '1388', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmpbeqmgk2t']
[2023-12-23T16:47:18.312+0000] {standard_task_runner.py:88} INFO - Job 1388: Subtask run_dbt
[2023-12-23T16:47:18.361+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.run_dbt manual__2023-12-23T16:37:11.087925+00:00 [running]> on host 417a45a22e6c
[2023-12-23T16:47:18.437+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='10 academy' AIRFLOW_CTX_DAG_ID='dag_to_dum_raw_data_to_postgres' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T16:37:11.087925+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-23T16:37:11.087925+00:00'
[2023-12-23T16:47:18.439+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-23T16:47:18.440+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt_run']
[2023-12-23T16:47:18.452+0000] {subprocess.py:86} INFO - Output:
[2023-12-23T16:47:18.454+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt_run: command not found
[2023-12-23T16:47:18.455+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-23T16:47:18.468+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-23T16:47:18.473+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_to_dum_raw_data_to_postgres, task_id=run_dbt, execution_date=20231223T163711, start_date=20231223T164718, end_date=20231223T164718
[2023-12-23T16:47:18.495+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1388 for task run_dbt (Bash command failed. The command returned a non-zero exit code 127.; 819)
[2023-12-23T16:47:18.512+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T16:47:18.690+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
