[2023-12-23T14:46:40.001+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.run_dbt manual__2023-12-23T14:27:38.614254+00:00 [queued]>
[2023-12-23T14:46:40.016+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_to_dum_raw_data_to_postgres.run_dbt manual__2023-12-23T14:27:38.614254+00:00 [queued]>
[2023-12-23T14:46:40.016+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-23T14:46:40.173+0000] {taskinstance.py:2192} INFO - Executing <Task(BashOperator): run_dbt> on 2023-12-23 14:27:38.614254+00:00
[2023-12-23T14:46:40.179+0000] {standard_task_runner.py:60} INFO - Started process 230 to run task
[2023-12-23T14:46:40.184+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_to_dum_raw_data_to_postgres', 'run_dbt', 'manual__2023-12-23T14:27:38.614254+00:00', '--job-id', '1313', '--raw', '--subdir', 'DAGS_FOLDER/dump_raw_data_to_postgres.py', '--cfg-path', '/tmp/tmpigfoep86']
[2023-12-23T14:46:40.188+0000] {standard_task_runner.py:88} INFO - Job 1313: Subtask run_dbt
[2023-12-23T14:46:40.248+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_to_dum_raw_data_to_postgres.run_dbt manual__2023-12-23T14:27:38.614254+00:00 [running]> on host 417a45a22e6c
[2023-12-23T14:46:40.348+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='10 academy' AIRFLOW_CTX_DAG_ID='dag_to_dum_raw_data_to_postgres' AIRFLOW_CTX_TASK_ID='run_dbt' AIRFLOW_CTX_EXECUTION_DATE='2023-12-23T14:27:38.614254+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-23T14:27:38.614254+00:00'
[2023-12-23T14:46:40.351+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-23T14:46:40.352+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'dbt_run']
[2023-12-23T14:46:40.365+0000] {subprocess.py:86} INFO - Output:
[2023-12-23T14:46:40.368+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: dbt_run: command not found
[2023-12-23T14:46:40.369+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-12-23T14:46:40.382+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-12-23T14:46:40.387+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_to_dum_raw_data_to_postgres, task_id=run_dbt, execution_date=20231223T142738, start_date=20231223T144640, end_date=20231223T144640
[2023-12-23T14:46:40.403+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 1313 for task run_dbt (Bash command failed. The command returned a non-zero exit code 127.; 230)
[2023-12-23T14:46:40.436+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-23T14:46:40.452+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
